// src/services/metricsService.ts
'use server';

import type { LucideIcon } from "lucide-react";
import { 
  DollarSign, 
  UserPlus, 
  Repeat, 
  Database,
  FileUp,
  Lightbulb,
  FilePlus2,
  Users
} from "lucide-react";
import type { StatCardProps } from "@/components/dashboard/StatCard";
import type { InsightCardProps } from "@/components/dashboard/InsightCard";
import type { DataSourceCardProps } from "@/components/dashboard/DataSourceCard";

// In a real application, this data would be fetched from a database (e.g., Firestore).
// These functions simulate that data fetching process.

// --- Mock Data ---

const mockStats: StatCardProps[] = [
  { title: "Monthly Sales", value: "$45,231.89", icon: DollarSign, change: "+20.1%", changeType: "increase" as const },
  { title: "New Users", value: "+1,234", icon: UserPlus, change: "+15.2%", changeType: "increase" as const },
  { title: "Recurring Users", value: "8,765", icon: Repeat, change: "-1.2%", changeType: "decrease" as const },
  { title: "Data Sources", value: "12", icon: Database, change: "+2", changeType: "increase" as const },
];

const mockActivity = [
  {
    id: "act1",
    user: { name: "Alice" },
    action: "uploaded a new data source",
    target: "Q4 Sales Report.csv",
    time: "5m ago",
    icon: FileUp,
  },
  {
    id: "act2",
    user: { name: "AI Assistant" },
    action: "generated a new insight about",
    target: "User Engagement Trends",
    time: "30m ago",
    icon: Lightbulb,
  },
  {
    id: "act3",
    user: { name: "Bob" },
    action: "created a new report",
    target: "Weekly Marketing KPIs",
    time: "2h ago",
    icon: FilePlus2,
  },
  {
    id: "act4",
    user: { name: "Alice" },
    action: "added 3 new team members",
    target: "",
    time: "1d ago",
    icon: Users,
  },
];

const mockDataSources: DataSourceCardProps[] = [
  { id: "ds1", name: "Sales Q3 Data", type: "File", freshness: "Updated 5 mins ago", rowCount: 150234, schemaSummary: "12 columns, 3 indexed", status: "ok" },
  { id: "ds2", name: "Customer Database", type: "Database", freshness: "Syncing...", rowCount: 87650, schemaSummary: "25 columns, 8 indexed", status: "syncing" },
  { id: "ds3", name: "Marketing API", type: "API", freshness: "Last checked 1 day ago", rowCount: 500000, schemaSummary: "8 fields", status: "error" },
];

const mockInsights: InsightCardProps[] = [
  { 
    id: "in1", 
    title: "User Engagement Analysis", 
    description: "Session duration is down 5% week-over-week. Further investigation into user feedback channels is recommended to understand the cause.",
    chartImage: "https://placehold.co/400x225.png",
    dataAiHint: "analytics graph"
  },
  { 
    id: "in2", 
    title: "Marketing Campaign Performance", 
    description: "The 'Summer Sale' campaign is driving the highest conversion rate, while 'Social Media Ads' have the best reach.", 
    chartImage: "https://placehold.co/400x225.png", 
    dataAiHint: "marketing results" 
  },
  { 
    id: "in3", 
    title: "Product Category Breakdown", 
    description: "Electronics continue to be the top-selling category, followed by Apparel.", 
    chartImage: "https://placehold.co/400x225.png", 
    dataAiHint: "sales analysis" 
  },
  { 
    id: "in4", 
    title: "Customer Churn Risk", 
    description: "A segment of 50 users who have not logged in for 30 days has been identified as high risk for churn.",
    chartImage: "https://placehold.co/400x225.png",
    dataAiHint: "customer data"
  },
  { 
    id: "in5", 
    title: "API Usage Spike", 
    description: "The primary data API experienced a 300% spike in requests yesterday at 3:00 PM. The system remained stable.",
    chartImage: "https://placehold.co/400x225.png",
    dataAiHint: "api data"
  },
];


// --- Service Functions ---

/**
 * Fetches high-level statistics for the main dashboard.
 * In a real app, this would query aggregated data.
 */
export async function getDashboardStats() {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));
  return mockStats;
}

/**
 * Fetches the most recent activity across the platform.
 */
export async function getRecentActivity() {
  await new Promise(resolve => setTimeout(resolve, 500));
  return mockActivity;
}

/**
 * Fetches the latest insights generated by the AI or users.
 */
export async function getLatestInsights() {
  await new Promise(resolve => setTimeout(resolve, 500));
  return mockInsights;
}

/**
 * Fetches a summary of the user's data sources.
 */
export async function getDataSourcesSummary() {
  await new Promise(resolve => setTimeout(resolve, 500));
  return mockDataSources;
}
